// <auto-generated />
namespace WEPresentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update26112016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update26112016));
        
        string IMigrationMetadata.Id
        {
            get { return "201611260242277_Update26112016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
